### PR TITLE
Migrate bundler based project

### PR DESCRIPTION
**Pull request by cosmo0920**
Before adding CI service(s), we should tidy up gem dependency with bundler to simplify preparing CI tasks.
After Applying these patches, we can execute tests the following commands:

```log
$ bundle install
$ bundle exec rake test
```

### CODE REVIEW

**Comment by djberg96** [comment]
@cosmo0920 If it's ok, I'll transfer this project to you and add you as an owner. Same for windows-pr.

But, you'll need to delete your fork first.

**Comment by cosmo0920** [comment]
> If it's ok, I'll transfer this project to you and add you as an owner. Same for windows-pr.

OK. :)

**Comment by cosmo0920** [comment]
@djberg96 Could you add me to windows-api and windows-pr gem ownership in rubygems.org?

**Comment by cosmo0920** [comment]
Can I merge this?

**Comment by djberg96** [comment]
@cosmo0920 I added you. Let me know if you have any problems.

**Comment by cosmo0920** [comment]
@djberg96 Thanks!

**Pull request merged**
